name: HouseCat Contract CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and lint
    env:
      POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Hardhat Build
        run: npm run build
      - name: Run linter and check formatting
        run: |
          npm run lint
          npm run format-check
      - name: Run unit tests
        run: npm test
